on:
  push:

jobs:
  build:
    name: Run Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: TypeStrong/typedoc-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
